name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [staging]
  pull_request:
    branches: [staging]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Copy the app to correcct folder
      - name: git pull on lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/html/hpvk && git pull https://${{ secrets.GIT_PULL_USER }}:${{ secrets.GIT_PULL_PASS }}@github.com/vankatwijk/hpvk-urlshortener-filetransfer-tempemail-laravel-vue.git
            cd /var/www/html/hpvk && echo $(date -u) > lastupdated.json
            cd /var/www/html/hpvk && php artisan storage:link && php artisan key:generate && php artisan migrate
            cd /var/www/html/hpvk && npm i && npm run prod
